<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magezon\Blog\Block\Product\RelatedPosts;
use Magezon\Blog\Helper\Data as DataHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** This file should have been called related_posts */
/** @var RelatedPosts $block */
/** @var Escaper $escaper */

/** @var DataHelper $dataHelper */
$dataHelper = $this->helper(DataHelper::class);

$html = $block->getPostListHtml();
$title = $dataHelper->getConfig('product_page/related_posts/title');
?>
<?php if ($html) { ?>
    <div class="blog-block blog-product-relatedposts container">
        <?php if ($title) { ?>
            <div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300">
                <h3 class="text-gray-900 text-xl title-font font-base text-center md:text-left w-full">
                    <?= $escaper->escapeHtml($title) ?>
                </h3>
            </div>
        <?php } ?>
        <div class="blog-block-content grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <?= /** @noEscape */ $html ?>
        </div>
    </div>
<?php } ?>
