<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\MagezonBlog\ViewModel\BlogFullPageCacheTags;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var BlogFullPageCacheTags $cacheTags */
$cacheTags = $viewModels->require(BlogFullPageCacheTags::class);


/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$items = $block->getCollection();
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}

?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.js_slides');
            },
            pageSize: 4,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.js_slide').length;
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const sliderItems = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            }
        }
    }
</script>
<section class="<?=
$escaper->escapeHtmlAttr($block->getData('maybe_purged_tailwind_section_classes'))
    ?: 'mb-6 text-gray-700 body-font';
?>"
         x-data="initSliderComponent()"
         x-init="calcPageSize();"
         @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
>
    <?php if ($items): ?>
        <div class="relative">
            <div id="blog-featured-posts" class="blog-block blog-featured-posts">
                <div class="block-block-title ">
                    <h3 class="title-font sm:text-xl text-lg mb-2 font-bold text-gray-900">
                        <?= $block->getFeaturedPostsTitleConfig() ?? __('Featured Posts') ?></h3>
                </div>
            </div>
            <div class="card card-interactive">
                <div class="relative w-full overflow-x-hidden focus-within:ring-1 active:ring-0 ring-blue-500/50">
                    <div class="relative flex flex-nowrap w-full overflow-auto js_slides snap"
                         @scroll.debounce="calcActive"
                    >
                        <?php foreach ($items as $item): ?>
                            <?php $cacheTags->register($item); ?>
                            <div class="flex shrink-0 w-full py-1 js_slide">
                                <div class="">
                                    <div class="blog-post-box">
                                        <div class="blog-post-box-inner">
                                            <?php if(!empty($item->getImageUrl())) :?>
                                                <div class="blog-post-image">
                                                    <a href="<?= $item->getUrl() ?>" title="<?= $block->escapeHtml($item->getTitle()) ?>">
                                                        <img src="<?= $block->escapeUrl($item->getImageUrl()) ?>" class="owl-lazy" data-src="<?= $block->escapeUrl($item->getImageUrl()) ?>"
                                                             alt="<?= $block->escapeHtml($item->getTitle()) ?>" width="600" height="400"/>
                                                    </a>
                                                </div>
                                            <?php endif; ?>
                                            <h3 class="blog-post-box-title title-font text-sm my-2 font-semibold text-gray-600">
                                                <a href="<?= $item->getUrl() ?>" title="<?= $block->escapeHtml($item->getTitle()) ?>"><?= $item->getTitle() ?></a>
                                            </h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 0
                            }"></div>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 1
                            }"></div>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 2
                            }"></div>
                    </div>
                </div>
                <div>
                    <template x-if="itemCount > pageSize">
                        <div class="flex items-center justify-center pt-0 pb-2">
                            <div class="flex flex-wrap w-full md:w-auto justify-center">
                                <?php for ($i=0; $i < $itemCount; $i++): ?>
                                    <span class="shrink-0 block w-3 h-3 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                          :class="{
                                        'bg-opacity-100': active === <?= (int) $i ?>,
                                        'hidden': (pageSize !== 1 && !!(<?= (int) $i ?> % pageSize))
                                        }"
                                          @click="scrollTo(<?= (int) $i ?>)">
                            </span>
                                <?php endfor; ?>
                            </div>
                        </div>
                    </template>
                </div>
            </div>
        </div>
    <?php endif; ?>
</section>
