<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\MagezonBlog\ViewModel\BlogFullPageCacheTags;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magezon\Blog\Api\Data\PostInterface;
use Magezon\Blog\Block\ListPost;
use Magezon\Blog\Helper\Data as DataHelper;
use Magezon\Blog\Model\Comment;
use Magezon\Blog\Model\Post;
use Magezon\Core\Helper\Data as CoreHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Magento2.Files.LineLength, Generic.Files.LineLength

/** @var ListPost $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CoreHelper $coreHelper */
$coreHelper = $this->helper(CoreHelper::class);
/** @var DataHelper $dataHelper */
$dataHelper = $this->helper(DataHelper::class);

/** @var HeroiconsOutline $heroiconsOutline */
$heroiconsOutline = $viewModels->require(HeroiconsOutline::class);

/** @var BlogFullPageCacheTags $cacheTags */
$cacheTags = $viewModels->require(BlogFullPageCacheTags::class);

$uid = 'blog-' . time() . uniqid();
$commentType = $dataHelper->getCommentType();
$collection = $block->getCollection();
$count = $collection->count();
$showAuthor = $block->getShowAuthor();
$showDate = $block->getShowDate();
$showImage = $block->getShowImage();
$showCategory = $block->getShowCategory();
$showComment = $block->getShowComment();
$showView = $block->getShowView();
$showExcerpt = $block->getShowExcerpt();
$showReadTime = $this->getShowReadTime();
$layout = $block->getListLayout() ? $block->getListLayout() : Post::LAYOUT_FIXED_THUMBNAIL;

$column = '';
$col = 1;
if ($layout == Post::LAYOUT_GRID || $layout == Post::LAYOUT_MASONRY) {
    $col = $block->getListColumn() ? (int)$block->getListColumn() : 3;
    $column = $block->getListColumn() ? 'xl:grid-cols-' . $col . ' lg:grid-cols-' . max($col-1, 1) . ' md:grid-cols-' . max($col-2, 1) . ' grid-cols-' . max($col-3, 1) : '';
}

$noResultText = $block->getNoResultText() ? $block->getNoResultText() : __('We can\'t find posts matching the selection.');

$imageWidth = 800;
$imageHeight = 450;

if ($layout === Post::LAYOUT_FULL_THUMBNAIL) {
    $imageWidth = 1000;
    $imageHeight = 563;
}
/**
 * We're listing Tailwind Classes here so that Tailwind Purge can pick them up.
 * This grid potentially renders:
 * grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-5 grid-cols-6
 * md:grid-cols-1 md:grid-cols-2 md:grid-cols-3 md:grid-cols-4
 * lg:grid-cols-1 lg:grid-cols-2 lg:grid-cols-3 lg:grid-cols-4 lg:grid-cols-5
 * xl:grid-cols-1 xl:grid-cols-2 xl:grid-cols-3 xl:grid-cols-4 xl:grid-cols-5 xl:grid-cols-6
 */
?>
<div class="blog-post-list">
    <div id="<?= $escaper->escapeHtmlAttr($uid) ?>"
         class="mb-5 blog-post-listing blog-post-list-layout-<?= $escaper->escapeHtmlAttr($layout) ?> grid gap-4 <?= $escaper->escapeHtmlAttr($column) ?>">
        <?php if ($count) { ?>
            <?php /** @var PostInterface $post */ ?>
            <?php foreach ($collection as $post) { ?>
                <?php $cacheTags->register($post); ?>
                <div class="blog-post-box blog-post-type-<?= $escaper->escapeHtmlAttr($post->getType()) ?>">
                    <div class="blog-post-box-inner flex flex-wrap card pb-4 h-full">
                        <?php if ((
                                $layout == Post::LAYOUT_FULL_THUMBNAIL ||
                                $layout == Post::LAYOUT_GRID ||
                                $layout == Post::LAYOUT_MASONRY
                                ) && (
                                    $showImage &&
                                    (
                                        $imageUrl = $post->getImageUrl($imageWidth, $imageHeight)
                                    )
                                )
                            ) { ?>
                            <div class="blog-post-image w-full mb-4">
                                <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                                   title="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                                >
                                    <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($imageUrl)) ?>"
                                         alt="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                                         loading="lazy"
                                         width="<?= (int) $imageWidth ?>"
                                         height="<?= (int) $imageHeight ?>"
                                         class="w-full"
                                    />
                                    <span class="blog-post-overlay"></span></a>
                            </div>
                        <?php } ?>
                        <h2 class="blog-post-box-title title-font sm:text-2xl text-xl mb-1 font-medium text-gray-900 w-full">
                            <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                               title="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                            >
                                <?= $escaper->escapeHtml($post->getTitle()) ?>
                            </a>
                        </h2>
                        <?php if ($showAuthor || $showDate || $showCategory || $showComment) { ?>
                            <div class="blog-post-meta w-full mb-4">
                                <?php if ($showAuthor && ($author = $post->getAuthor())) { ?>
                                    <span class="blog-post-meta-author inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                        <?= $heroiconsOutline->userCircleHtml('flex-shrink-0', 18, 18) ?>
                                        <?php if ($author->getUrl()) { ?>
                                        <a
                                            href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($author->getUrl())) ?>"
                                            title="<?= $escaper->escapeHtmlAttr($author->getPublicName()) ?>"
                                            class="hover:underline"
                                        >
                                        <?php } ?>
                                        <?= $escaper->escapeHtml($author->getPublicName()) ?>
                                        <?php if ($author->getUrl()) { ?>
                                        </a>
                                        <?php } ?>
                                    </span>
                                <?php } ?>
                                <?php if ($showDate) { ?>
                                    <span class="blog-post-meta-date inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                        <?= $heroiconsOutline->clockHtml('flex-shrink-0', 18, 18) ?>
                                        <?= $escaper->escapeHtml($post->getCreatedAtFormatted(true)) ?>
                                    </span>
                                <?php } ?>
                                <?php if ($showCategory) { ?>
                                    <?php $categories = $post->getCategoryList() ?>
                                    <?php if ($categories) { ?>
                                        <span class="blog-post-meta-cats inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                        <?= $heroiconsOutline->folderHtml('', 18, 18) ?>
                                        <span>
                                            <?php foreach ($categories as $key => $category) { ?>
                                            <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($category->getUrl())) ?>"
                                               data-id="<?= $escaper->escapeHtmlAttr($key) ?>"
                                               class="hover:underline inline-block"
                                            >
                                                <?= $escaper->escapeHtml($category->getTitle()) ?>
                                                </a><?= (isset($categories[$key + 1]) && $categories[$key + 1]) ? ', ' : '' ?>
                                            <?php } ?>
                                        </span>
                                    </span>
                                    <?php } ?>
                                <?php } ?>
                                <?php if ($showView) { ?>
                                    <span class="blog-post-meta-views inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                        <?= $heroiconsOutline->eyeHtml('flex-shrink-0', 18, 18) ?>
                                        <?= (int) $post->getTotalViews() ?>
                                    </span>
                                <?php } ?>
                                <?php if ($showComment && $post->getAllowComment() && ($commentType !== Comment::TYPE_FACEBOOK)) { ?>
                                    <?php $totalCommentCount = (int) $post->getTotalComments(); ?>
                                    <span class="blog-post-meta-comments inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                        <?= $heroiconsOutline->renderHtml('chat-alt-2', 'flex-shrink-0', 18, 18) ?>
                                        <a href="<?= $escaper->escapeUrl($post->getMetaCommentUrl()) ?>"
                                           class="hover:underline"
                                        >
                                            <?= (int) $post->getTotalComments() ?>
                                        </a>
                                    </span>
                                <?php } ?>
                                <?php if ($showReadTime && !empty($post->getReadTime())) { ?>
                                    <span class="blog-post-meta-read-time inline-flex items-center text-gray-700 mr-4 gap-x-1 text-sm">
                                    <?= $heroiconsOutline->bookOpenHtml('', 18, 18) ?>
                                    <?= $block->escapeHtml($post->getReadTime()) ?> <?= __('Min read') ?></span>
                                <?php } ?>
                            </div>
                        <?php } ?>
                        <?php if (($layout == Post::LAYOUT_FIXED_THUMBNAIL) && ($showImage && ($imageUrl = $post->getImageUrl($imageWidth, $imageHeight)))) { ?>
                            <div class="blog-post-image w-full <?php if ($col===1): ?>lg:w-2/5 mb-4 lg:mb-0<?php endif;?>">
                                <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                                   title="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                                   class="-mx-4 lg:mx-0 block"
                                >
                                    <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($imageUrl)) ?>"
                                         class="w-full h-auto"
                                         alt="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                                         loading="lazy"
                                         width="<?= (int) $imageWidth ?>"
                                         height="<?= (int) $imageHeight ?>"
                                    />
                                    <span class="blog-post-overlay"></span>
                                </a>
                            </div>
                        <?php } ?>
                        <?php if ($showExcerpt) { ?>
                            <div class="blog-post-excerpt-wrapper w-full <?php if ($col===1): ?>lg:w-3/5 px-2 md:px-0 md:pl-4<?php endif; ?>">
                                <?php if ($excerpt = $post->getPostExcerpt()) { ?>
                                    <div class="blog-post-excerpt mb-2">
                                        <?= /** @noEscape  */ $excerpt ?>
                                    </div>
                                <?php } ?>
                                <a class="blog-post-more-link btn btn-primary inline-flex"
                                   href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                                >
                                    <?= $escaper->escapeHtml(__('Read Post')) ?>
                                    <?= $heroiconsOutline->chevronDoubleRightHtml('ml-2', 18, 18) ?>
                                </a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        <?php } elseif ($noResultText) { ?>
            <div class="blog-noresult">
                <?= $escaper->escapeHtml($noResultText) ?>
            </div>
        <?php } ?>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="amrelated-bundle-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml() ?></div>
    <?php endif ?>
</div>
