<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\MagezonBlog\ViewModel\BlogFullPageCacheTags;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magezon\Blog\Api\Data\PostInterface;
use Magezon\Blog\Block\ListPost;
use Magezon\Blog\Helper\Data as DataHelper;
use Magezon\Blog\Model\Comment;
use Magezon\Core\Helper\Data as CoreHelper;

/** @var ListPost $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CoreHelper $coreHelper */
$coreHelper = $this->helper(CoreHelper::class);
/** @var DataHelper $dataHelper */
$dataHelper = $this->helper(DataHelper::class);
/** @var BlogFullPageCacheTags $cacheTags */
$cacheTags = $viewModels->require(BlogFullPageCacheTags::class);

/** @var HeroiconsOutline $heroiconsOutline */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$viewModelStore = $viewModels->require(Store::class);

$items = $block->getCollection();

if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}

$uid = 'blog-' . time() . uniqid();
$commentType = $dataHelper->getCommentType();
$collection = $block->getCollection();
$count = $collection->count();
$showAuthor = $block->getShowAuthor();
$showDate = $block->getShowDate();
$showImage = $block->getShowImage();
$showCategory = $block->getShowCategory();
$showComment = $block->getShowComment();
$showView = $block->getShowView();
$showExcerpt = $block->getShowExcerpt();
$carouselOptions = $block->getOwlCarouselOptions();
$showReadTime = $this->getShowReadTime();
$showReadTime = $this->getShowReadTime();

$imageWidth = 800;
$imageHeight = 450;
?>
    <script>
        'use strict';

        function initSliderComponent() {
            return {
                active: 0,
                itemCount: 0,
                getSlider() {
                    return this.$root.querySelector('.js_slides');
                },
                pageSize: 4,
                pageFillers: 0,
                calcPageSize() {
                    const slider = this.getSlider();
                    if (slider) {
                        this.itemCount = slider.querySelectorAll('.js_slide').length;
                        this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                        this.pageFillers = (
                            this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                        ) - this.itemCount;
                    }
                },
                calcActive() {
                    const slider = this.getSlider();
                    if (slider) {
                        const sliderItems = this.itemCount + this.pageFillers;
                        const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                        this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                    }
                },
                scrollPrevious() {
                    this.scrollTo(this.active - this.pageSize);
                },
                scrollNext() {
                    this.scrollTo(this.active + this.pageSize);
                },
                scrollTo(idx) {
                    const slider = this.getSlider();
                    if (slider) {
                        const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                        slider.scrollLeft = Math.floor(slideWidth) * idx;
                        this.active = idx;
                    }
                }
            };
        }
    </script>
    <section class="<?=
    $escaper->escapeHtmlAttr($block->getData('maybe_purged_tailwind_section_classes'))
        ?: 'text-gray-700 body-font';
    ?>"
             x-data="initSliderComponent()"
             x-init="calcPageSize();"
             @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
    >
        <?php if ($items): ?>
            <div class="relative">
                <div
                    class="flex-none relative w-full overflow-x-hidden focus-within:ring-2 ring-offset-2 active:ring-0 ring-blue-500/50">
                    <div class="relative flex flex-nowrap w-full overflow-auto js_slides snap md:px-1 xl:px-2"
                         @scroll.debounce="calcActive"
                    >
                        <?php foreach ($items as $post): ?>
                            <?php $cacheTags->register($post); ?>
                            <?php $author = $post->getAuthor() ?>
                            <div class="flex shrink-0 w-full mr-1 p-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4">
                                <div class="">
                                    <div class="blog-post-box card card-interactive min-h-[270px]">
                                        <div class="blog-post-box-inner">
                                            <?php if ($showImage && ($imageUrl = $post->getImageUrl($imageWidth, $imageHeight))) { ?>
                                                <div class="blog-post-image mb-2">
                                                    <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                                                       title="<?= $block->escapeHtml($post->getTitle()) ?>"
                                                    >
                                                        <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($imageUrl)) ?>"
                                                             alt="<?= $block->escapeHtml($post->getTitle()) ?>"
                                                             loading="lazy"
                                                             width="<?= (int) $imageWidth ?>"
                                                             height="<?= (int) $imageHeight ?>"
                                                        />
                                                    </a>
                                                </div>
                                            <?php } ?>
                                            <h3 class="blog-post-box-title title-font text-sm my-2 font-semibold text-gray-600">
                                                <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                                                   title="<?= $block->escapeHtml($post->getTitle()) ?>"
                                                >
                                                    <?= $escaper->escapeHtml($post->getTitle()) ?>
                                                </a>
                                            </h3>
                                            <?php if ($showAuthor || $showDate || $showCategory || $showComment || $showReadTime) { ?>
                                                <div class="blog-post-meta">
                                                    <?php if ($showAuthor && $author) { ?>
                                                        <span class="blog-post-meta-author inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                                            <?= $heroicons->userCircleHtml('', 18, 18) ?>
                                                                                        <?php if ($authorUrl = $author->getUrl()) { ?>
                                                            <a
                                                                href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($authorUrl)) ?>"
                                                                title="<?= $block->escapeHtml($author->getPublicName()) ?>"
                                                            >
                                                            <?php } ?>
                                                            <?= $escaper->escapeHtml($author->getPublicName()) ?>
                                                            <?php if ($author->getUrl()) { ?>
                                                            </a>
                                                            <?php } ?>
                                                        </span>
                                                    <?php } ?>

                                                    <?php if ($showDate) { ?>
                                                        <span class="blog-post-meta-date inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                                            <?= $heroicons->clockHtml('', 18, 18) ?>
                                                            <?= $escaper->escapeHtml($post->getCreatedAtFormatted(true)) ?>
                                                        </span>
                                                    <?php } ?>

                                                    <?php if ($showCategory) { ?>
                                                        <?php $categories = $post->getCategoryList() ?>
                                                        <?php if ($categories) { ?>
                                                            <span class="blog-post-meta-cats inline-flex  items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                                                <?= $heroicons->folderHtml('', 18, 18) ?>
                                                                <span>
                                                                    <?php foreach ($categories as $key => $category) { ?>
                                                                    <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($category->getUrl())) ?>"
                                                                       data-id="<?= $escaper->escapeHtmlAttr($key) ?>"
                                                                       class="hover:underline inline-block"
                                                                    >
                                                                        <?= $escaper->escapeHtml($category->getTitle()) ?>
                                                                        </a><?= (isset($categories[$key + 1]) && $categories[$key + 1]) ? ', ' : '' ?>
                                                                    <?php } ?>
                                                                </span>
                                                            </span>
                                                        <?php } ?>
                                                    <?php } ?>

                                                    <?php if ($showView) { ?>
                                                        <span class="blog-post-meta-views inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                                            <?= $heroicons->eyeHtml('', 18, 18) ?>
                                                            <?= (int) $post->getTotalViews() ?>
                                                        </span>
                                                    <?php } ?>

                                                    <?php if ($showComment && $post->getAllowComment() && ($commentType !== Comment::TYPE_FACEBOOK)) { ?>
                                                        <span class="blog-post-meta-comments inline-flex items-center text-gray-700 mr-2 gap-x-1 text-sm">
                                                            <?= $heroicons->renderHtml('chat-alt-2', '-', 18, 18) ?>
                                                            <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getMetaCommentUrl())) ?>"
                                                               class="hover:underline"
                                                            >
                                                                <?= (int) $post->getTotalComments() ?>
                                                            </a>
                                                        </span>
                                                    <?php } ?>

                                                    <?php if ($showReadTime && !empty($post->getReadTime())) { ?>
                                                        <span class="blog-post-meta-read-time inline-flex items-center text-gray-700 mr-4 gap-x-1 text-sm">
                                                            <?= $heroicons->bookOpenHtml('', 18, 18) ?>
                                                            <?= $block->escapeHtml($post->getReadTime()) ?> <?= __('Min read') ?>
                                                        </span>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>

                                            <?php if ($showExcerpt) { ?>
                                                <div class="blog-post-excerpt-wrapper mb-2">
                                                    <?php if ($excerpt = $post->getPostExcerpt()) { ?>
                                                        <div class="blog-post-excerpt my-3">
                                                            <?= /** @noEscape */ $excerpt ?>
                                                        </div>
                                                    <?php } ?>
                                                    <a class="blog-post-more-link btn btn-primary inline-flex"
                                                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getUrl())) ?>"
                                                    >
                                                        <?= $escaper->escapeHtml(__('Read More »')) ?>
                                                    </a>
                                                </div>
                                            <?php } ?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex shrink-0 py-1' : pageFillers > 0
                        }"></div>
                        <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex shrink-0 py-1' : pageFillers > 1
                        }"></div>
                        <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex shrink-0 py-1' : pageFillers > 2
                        }"></div>
                    </div>
                </div>
                <div style="min-height: 65px">
                    <template x-if="itemCount > pageSize">
                        <div class="flex items-center justify-center py-4">
                            <button
                                aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                                tabindex="-1"
                                class="mr-4 text-black rounded-full outline-none focus:outline-none flex-none"
                                :class="{ 'opacity-25 pointer-events-none' : active === 0 }"
                                @click="scrollPrevious">
                                <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                            </button>
                            <div class="flex flex-wrap w-full md:w-auto justify-center">
                                <?php for ($i = 0; $i < $itemCount; $i++): ?>
                                    <span
                                        class="shrink-0 block w-3 h-3 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                        :class="{
                                    'bg-opacity-100': active === <?= (int)$i ?>,
                                    'hidden': (pageSize !== 1 && !!(<?= (int)$i ?> % pageSize))
                                    }"
                                        @click="scrollTo(<?= (int)$i ?>)">
                        </span>
                                <?php endfor; ?>
                            </div>
                            <button
                                aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                                tabindex="-1"
                                class="ml-4 text-black rounded-full outline-none focus:outline-none flex-none"
                                :class="{ 'opacity-25 pointer-events-none' : active >= itemCount-pageSize }"
                                @click="scrollNext">
                                <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                            </button>
                        </div>
                    </template>
                </div>
            </div>
        <?php endif; ?>
    </section>
<?php
