<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Helper\Product\Compare as CompareHelper;
use Magento\Framework\Escaper;
use Magento\Wishlist\Helper\Data as WishlistHelper;
use Magezon\Blog\Block\Post\RelatedProducts;
use Magezon\Blog\Helper\Data as DataHelper;
use Magezon\Core\Helper\Data as CoreHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Magento2.Files.LineLength, Generic.Files.LineLength

/** @var RelatedProducts $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CoreHelper $coreHelper */
$coreHelper = $this->helper(CoreHelper::class);
/** @var DataHelper $dataHelper */
$dataHelper = $this->helper(DataHelper::class);
/** @var CompareHelper $compareHelper */
$compareHelper = $this->helper(CompareHelper::class);
/** @var WishlistHelper $wishlistHelper */
$wishlistHelper = $this->helper(WishlistHelper::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var HeroiconsOutline $heroiconsOutline */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$id = time() . uniqid();
$showImage = true;
$showName = true;
$showPrice = true;
$showShortDescription = false;
$showWishlist = true;
$showCompare = true;
$showCart = true;
$showReview = true;
$imageId = 'category_page_grid';
$templateType = ReviewRendererInterface::SHORT_VIEW;
$title = $dataHelper->getConfig('post_page/related_products/title');

$items = $block->getCollection();
$count = $items->count();

if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}
?>
<?php if ($count) { ?>
    <div class="blog-block blog-post-relatedproducts mb-8">
        <?php if ($title) { ?>
            <div class="blog-block-title">
                <h3 class="title-font sm:text-xl text-lg mb-1 text-gray-900 font-bold">
                    <?= $escaper->escapeHtml($title) ?>
                </h3>
            </div>
        <?php } ?>
        <script>
            'use strict';

            function initSliderComponent() {
                return {
                    active: 0,
                    itemCount: 0,
                    getSlider() {
                        return this.$root.querySelector('.js_slides');
                    },
                    pageSize: 3,
                    pageFillers: 0,
                    calcPageSize() {
                        const slider = this.getSlider();
                        if (slider) {
                            this.itemCount = slider.querySelectorAll('.js_slide').length;
                            this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                            this.pageFillers = (
                                this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                            ) - this.itemCount;
                        }
                    },
                    calcActive() {
                        const slider = this.getSlider();
                        if (slider) {
                            const sliderItems = this.itemCount + this.pageFillers;
                            const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                            this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                        }
                    },
                    scrollPrevious() {
                        this.scrollTo(this.active - this.pageSize);
                    },
                    scrollNext() {
                        this.scrollTo(this.active + this.pageSize);
                    },
                    scrollTo(idx) {
                        const slider = this.getSlider();
                        if (slider) {
                            const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                            slider.scrollLeft = Math.floor(slideWidth) * idx;
                            this.active = idx;
                        }
                    }
                };
            }
        </script>
        <section class="<?=
        $escaper->escapeHtmlAttr($block->getData('maybe_purged_tailwind_section_classes'))
            ?: 'text-gray-700 body-font';
        ?>"
                 x-data="initSliderComponent()"
                 x-init="calcPageSize();"
                 @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
        >
            <div class="relative">
                <div
                    class="flex-none relative w-full overflow-x-hidden focus-within:ring-2 ring-offset-2 active:ring-0 ring-blue-500/50">
                    <div class="relative flex flex-nowrap w-full overflow-auto js_slides snap md:px-1 xl:px-2"
                         @scroll.debounce="calcActive"
                    >
                        <?php foreach ($items as $product): ?>
                            <div class="flex shrink-0 w-full mr-1 p-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/3">
                                <div class="">
                                    <div class="item product product-item card card-interactive">
                                        <div class="product-item-info">
                                            <?php if ($showImage) { ?>
                                                <?php $productImage = $block->getImage($product, $imageId, ['loading' => 'lazy']); ?>
                                                <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                                                   class="product photo product-item-photo"
                                                   tabindex="-1"
                                                >
                                                    <?= $productImage->toHtml(); ?>
                                                </a>
                                            <?php } ?>
                                            <div class="product details product-item-details">
                                                <?php if ($showName) { ?>
                                                    <p class="product-item-name flex items-center justify-center px-1 pt-3 text-primary">
                                                        <a title="<?= $escaper->escapeHtml($product->getName()) ?>"
                                                           href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getProductUrl($product))) ?>"
                                                           class="product-item-link">
                                                            <?= $escaper->escapeHtml($product->getName()) ?>
                                                        </a>
                                                    </p>
                                                <?php } ?>

                                                <div class="pt-1 text-lg text-center justify-center text-gray-900">
                                                    <?= $showPrice ? /** @noEscape */ $block->getProductPrice($product) : '' ?>
                                                </div>

                                                <?= ($templateType && $showReview)
                                                    ? $block->getReviewsSummaryHtml($product, $templateType)
                                                    : ''
                                                ?>

                                                <?php if ($showShortDescription) { ?>
                                                    <div class="product-item-shortdescription">
                                                        <?= /** @noEscape */ $coreHelper->filter($product->getShortDescription()) ?>
                                                    </div>
                                                <?php } ?>

                                                <?php if ($showWishlist || $showCompare || $showCart) { ?>
                                                    <div class="product-item-actions flex flex-wrap gap-2 inline p-3">
                                                        <?php if ($showCart) { ?>
                                                            <div class="actions-primary mr-auto">
                                                                <?php if ($product->isSaleable()) { ?>
                                                                    <?php $postParams = $block->getAddToCartPostParams($product); ?>
                                                                    <form data-role="tocart-form"
                                                                          action="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($postParams['action'])); ?>"
                                                                          method="post"
                                                                    >
                                                                        <input type="hidden" name="product"
                                                                               value="<?= (int) $postParams['data']['product'] ?>"
                                                                        />
                                                                        <input type="hidden"
                                                                               name="uenc"
                                                                               value="<?= $escaper->escapeHtmlAttr($postParams['data']['uenc']) ?>"
                                                                        />
                                                                        <?php if ($formKey = $block->getProductFormKey()) { ?>
                                                                            <input name="form_key"
                                                                                   type="hidden"
                                                                                   value="<?= $escaper->escapeHtmlAttr($formKey) ?>"
                                                                            />
                                                                        <?php } else { ?>
                                                                            <?= $block->getBlockHtml('formkey') ?>
                                                                        <?php } ?>
                                                                        <button type="submit"
                                                                                title="<?= $escaper->escapeHtml(__('Add to Cart')); ?>"
                                                                                class="action tocart primary justify-center w-auto mr-auto btn btn-primary"
                                                                        >
                                                                            <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                                        </button>
                                                                    </form>
                                                                <?php } else { ?>
                                                                    <?php if ($product->getIsSalable()) { ?>
                                                                        <div
                                                                            class="stock available flex items-center justify-end align-middle available gap-x-2"
                                                                        >
                                                                            <span class="w-3 h-3 bg-green-500 rounded-full flex-shrink-0"></span>
                                                                            <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                                        </div>
                                                                    <?php } else { ?>
                                                                        <div
                                                                            class="stock unavailable flex items-center justify-end align-middle available gap-x-2">
                                                                            <span class="w-3 h-3 bg-red-500 rounded-full flex-shrink-0"></span>
                                                                            <span>
                                                                <?= $escaper->escapeHtml(__('Out of stock')) ?>
                                                            </span>
                                                                        </div>
                                                                    <?php } ?>
                                                                <?php } ?>
                                                            </div>
                                                        <?php } ?>
                                                        <?php if ($showWishlist || $showCompare) { ?>
                                                            <div class="actions-secondary" data-role="add-to-links">
                                                                <?php if ($wishlistHelper->isAllow() && $showWishlist) { ?>
                                                                    <a href="#"
                                                                       x-data=""
                                                                       class="action towishlist rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex flex-shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2"
                                                                       @click.prevent='hyva.postForm(<?= /** @noEscape */ $block->getAddToWishlistParams($product) ?>)'
                                                                       data-action="add-to-wishlist"
                                                                       title="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                                    >
                                                        <span class="sr-only">
                                                            <?= $escaper->escapeHtml(__('Add to Wish List')) ?>
                                                        </span>
                                                                        <?= $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
                                                                    </a>
                                                                <?php } ?>
                                                                <?php if ($block->getAddToCompareUrl() && $showCompare) { ?>
                                                                    <a href="#"
                                                                       x-data=""
                                                                       class="action tocompare rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex flex-shrink-0 items-center justify-center text-gray-500 hover:text-yellow-500 ml-2"
                                                                       @click.prevent='hyva.postForm(<?= /** @noEscape */ $compareHelper->getPostDataParams($product) ?>)'
                                                                       title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                                    >
                                                                        <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                                                                        <?= $heroicons->scaleHtml("w-5 h-5", 25, 25) ?>
                                                                    </a>
                                                                <?php } ?>
                                                            </div>
                                                        <?php } ?>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex shrink-0 py-1' : pageFillers > 0
                        }"></div>
                        <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex shrink-0 py-1' : pageFillers > 1
                        }"></div>
                        <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex shrink-0 py-1' : pageFillers > 2
                        }"></div>
                    </div>
                </div>
                <div style="min-height: 65px">
                    <template x-if="itemCount > pageSize">
                        <div class="flex items-center justify-center py-4">
                            <button
                                aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                                tabindex="-1"
                                class="mr-4 text-black rounded-full outline-none focus:outline-none flex-none"
                                :class="{ 'opacity-25 pointer-events-none' : active === 0 }"
                                @click="scrollPrevious">
                                <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                            </button>
                            <div class="flex flex-wrap w-full md:w-auto justify-center">
                                <?php for ($i = 0; $i < $itemCount; $i++): ?>
                                    <span
                                        class="shrink-0 block w-3 h-3 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                        :class="{
                                    'bg-opacity-100': active === <?= (int)$i ?>,
                                    'hidden': (pageSize !== 1 && !!(<?= (int)$i ?> % pageSize))
                                    }"
                                        @click="scrollTo(<?= (int)$i ?>)">
                        </span>
                                <?php endfor; ?>
                            </div>
                            <button
                                aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                                tabindex="-1"
                                class="ml-4 text-black rounded-full outline-none focus:outline-none flex-none"
                                :class="{ 'opacity-25 pointer-events-none' : active >= itemCount-pageSize }"
                                @click="scrollNext">
                                <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                            </button>
                        </div>
                    </template>
                </div>
            </div>
        </section>
    </div>
<?php } ?>
