<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magezon\Blog\Block\Post\View;
use Magezon\Blog\Helper\Data as DataHelper;
use Magezon\Core\Helper\Data as CoreHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Magento2.Files.LineLength, Generic.Files.LineLength

/** @var View $block */
/** @var Escaper $escaper */

/** @var CoreHelper $coreHelper */
$coreHelper = $this->helper(CoreHelper::class);
/** @var DataHelper $dataHelper */
$dataHelper = $this->helper(DataHelper::class);

$post = $block->getCurrentPost();
$url = $post->getUrl();
$facebook = true;
$twitter = true;
$linkedin = true;
$pinterest = true;
?>
<?php if ($dataHelper->getConfig('post_page/social_box')) { ?>
    <div class="blog-post-social mt-8 flex items-center">
        <span class="font-semibold mr-4">
            <?= $escaper->escapeHtml(__('Share')) ?>:
        </span>
        <div class="blog-flat-social flex items-center gap-x-2 gap-y-2 flex-wrap">
            <?php if ($facebook) { ?>
                <a href="http://www.facebook.com/sharer.php?u=<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($url)) ?>"
                   class="tracking-widest social-facebook px-4 py-2 font-semibold text-white inline-flex items-center gap-x-2 rounded"
                   style="background-color: #1877f2; text-shadow: 0 0 2px black;"
                   rel="noreferrer"
                   target="_blank"
                   aria-label="<?= $escaper->escapeHtmlAttr(__('Facebook')) ?>"
                >
                    <svg class="w-5 h-5 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path
                            d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                    </svg>
                    <?= $escaper->escapeHtml(__('Facebook')) ?>
                </a>
            <?php } ?>
            <?php if ($twitter) { ?>
                <a href="https://twitter.com/intent/tweet?text=<?= $escaper->escapeHtml($post->getTitle()) ?>&url=<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($url)) ?>"
                   class="social-twitter px-4 py-2 font-semibold text-white inline-flex items-center gap-x-2 rounded"
                   style="background-color: #1da1f2; text-shadow: 0 0 2px black;"
                   rel="noreferrer"
                   target="_blank"
                   aria-label="<?= $escaper->escapeHtmlAttr(__('Twitter')) ?>"
                >
                    <svg class="w-5 h-5 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path
                            d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>
                    </svg>
                    <?= $escaper->escapeHtml(__('Twitter')) ?>
                </a>
            <?php } ?>
            <?php if ($linkedin) { ?>
                <a href="http://www.linkedin.com/shareArticle?mini=true&url=<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($url)) ?>&title=<?= $escaper->escapeHtml($post->getTitle()) ?>"
                   class="social-linkedin px-4 py-2 font-semibold text-white inline-flex items-center gap-x-2 rounded"
                   style="background-color: #0a66c2; text-shadow: 0 0 2px black;"
                   rel="noreferrer"
                   target="_blank"
                   aria-label="<?= $escaper->escapeHtmlAttr(__('LinkedIn')) ?>"
                >
                    <svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg"
                         viewBox="0 0 448 512" class="w-5 h-5 fill-current">
                        <path fill="currentColor"
                              d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"
                              class=""></path>
                    </svg>
                    <?= $escaper->escapeHtml(__('LinkedIn')) ?>
                </a>
            <?php } ?>
            <?php if ($pinterest) { ?>
                <a href="http://pinterest.com/pin/create/button/?url=<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($url)) ?>&amp;description=<?= $escaper->escapeHtml($post->getTitle()) ?>&amp;media=<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($post->getImageUrl())) ?>"
                   class="social-pinterest bg-pink-600 px-4 py-2 font-semibold text-white inline-flex items-center gap-x-2 rounded"
                   style="background-color: #bd081c; text-shadow: 0 0 2px black;"
                   rel="noreferrer"
                   target="_blank"
                   aria-label="<?= $escaper->escapeHtmlAttr(__('Pinterest')) ?>"
                >
                    <svg class="w-5 h-5 fill-current" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <title>Pinterest icon</title>
                        <path
                            d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.162-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.401.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.354-.629-2.758-1.379l-.749 2.848c-.269 1.045-1.004 2.352-1.498 3.146 1.123.345 2.306.535 3.55.535 6.607 0 11.985-5.365 11.985-11.987C23.97 5.39 18.592.026 11.985.026L12.017 0z"/>
                    </svg>
                    <?= $escaper->escapeHtml(__('Pinterest')) ?>
                </a>
            <?php } ?>
        </div>
    </div>
<?php } ?>
