<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magezon\Blog\Block\Author\View;
use Magezon\Blog\Helper\Image as ImageHelper;
use Magezon\Blog\Model\Author;
use Magezon\Core\Helper\Data as DataHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Magento2.Files.LineLength, Generic.Files.LineLength

/** @var View $block */
/** @var Escaper $escaper */

/** @var DataHelper $coreHelper */
$coreHelper = $this->helper(DataHelper::class);
/** @var ImageHelper $imageHelper */
$imageHelper = $this->helper(ImageHelper::class);

/** @var Author $author */
$author = $block->getCurrentAuthor();
$content = $coreHelper->filter($author->getContent());

$imageWidth = 100;
$imageHeight = 100;

$authorImageUrl = $author->getImage()
    ? $imageHelper->resize(
        $author->getImage(),
        $imageWidth * 2,
        $imageHeight * 2,
        100,
        'magezon/resized',
        ['keepAspectRatio' => true, 'keepFrame' => false]
    ) :
    '';
?>
<div class="blog-top-section blog-author-bio container card mb-8">
    <div class="blog-block-content blog-author-bio">
        <div class="blog-author-avatar float-left mr-4">
            <?php if ($author->getImage()): ?>
            <img alt="<?= $escaper->escapeHtmlAttr($author->getPublicName()) ?>"
                 src="<?= $escaper->escapeUrl($authorImageUrl) ?>"
                 height="<?= /** @noEscape  */ $imageWidth ?>"
                 width="<?= /** @noEscape  */ $imageHeight ?>"
                 loading="lazy"
            >
            <?php endif; ?>
        </div>
        <div>
            <?php if ($content) { ?>
                <div class="author-description">
                    <?= /** @noEscape */ $content ?>
                </div>
            <?php } ?>
            <div class="blog-author-social flat-social flex flex-wrap gap-2 mt-4">
                <?php if ($facebookUrl = $author->getFacebook()): ?>
                    <a class="social-facebook bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($facebookUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> Facebook
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                            <path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path>
                        </svg>
                    </a>
                <?php endif; ?>
                <?php if ($twitterHandle = $author->getTwitter()): ?>
                    <a class="social-twitter bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="http://twitter.com/<?= $escaper->escapeHtmlAttr($twitterHandle) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> Twitter
                        </span>
                        <svg class="w-5 h-5 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"></path>
                        </svg>
                    </a>
                <?php endif; ?>
                <?php if ($linkedinUrl = $author->getLinkedin()) { ?>
                    <a class="social-linkedin bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($linkedinUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> LinkedIn
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="linkedin-in" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z" class=""></path>
                        </svg>
                    </a>
                <?php } ?>
                <?php if ($flickrUrl = $author->getFlickr()) { ?>
                    <a class="social-flickr bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($flickrUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> Flickr
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="flickr" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M400 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zM144.5 319c-35.1 0-63.5-28.4-63.5-63.5s28.4-63.5 63.5-63.5 63.5 28.4 63.5 63.5-28.4 63.5-63.5 63.5zm159 0c-35.1 0-63.5-28.4-63.5-63.5s28.4-63.5 63.5-63.5 63.5 28.4 63.5 63.5-28.4 63.5-63.5 63.5z" class=""></path>
                        </svg>
                    </a>
                <?php } ?>
                <?php if ($youtubeUrl = $author->getYoutube()) { ?>
                    <a class="social-youtube bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($youtubeUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> YouTube
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="youtube" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                            <path fill="currentColor" d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z" class=""></path>
                        </svg>
                    </a>
                <?php } ?>
                <?php if ($pinterestUrl = $author->getPinterest()) { ?>
                    <a class="social-pinterest bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($pinterestUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> Pinterest
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="pinterest-p" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" >
                            <path fill="currentColor" d="M204 6.5C101.4 6.5 0 74.9 0 185.6 0 256 39.6 296 63.6 296c9.9 0 15.6-27.6 15.6-35.4 0-9.3-23.7-29.1-23.7-67.8 0-80.4 61.2-137.4 140.4-137.4 68.1 0 118.5 38.7 118.5 109.8 0 53.1-21.3 152.7-90.3 152.7-24.9 0-46.2-18-46.2-43.8 0-37.8 26.4-74.4 26.4-113.4 0-66.2-93.9-54.2-93.9 25.8 0 16.8 2.1 35.4 9.6 50.7-13.8 59.4-42 147.9-42 209.1 0 18.9 2.7 37.5 4.5 56.4 3.4 3.8 1.7 3.4 6.9 1.5 50.4-69 48.6-82.5 71.4-172.8 12.3 23.4 44.1 36 69.3 36 106.2 0 153.9-103.5 153.9-196.8C384 71.3 298.2 6.5 204 6.5z" class=""></path>
                        </svg>
                    </a>
                <?php } ?>
                <?php if ($behanceUrl = $author->getBehance()) { ?>
                    <a class="social-behance bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($behanceUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> Instagram
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="behance" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                            <path fill="currentColor" d="M232 237.2c31.8-15.2 48.4-38.2 48.4-74 0-70.6-52.6-87.8-113.3-87.8H0v354.4h171.8c64.4 0 124.9-30.9 124.9-102.9 0-44.5-21.1-77.4-64.7-89.7zM77.9 135.9H151c28.1 0 53.4 7.9 53.4 40.5 0 30.1-19.7 42.2-47.5 42.2h-79v-82.7zm83.3 233.7H77.9V272h84.9c34.3 0 56 14.3 56 50.6 0 35.8-25.9 47-57.6 47zm358.5-240.7H376V94h143.7v34.9zM576 305.2c0-75.9-44.4-139.2-124.9-139.2-78.2 0-131.3 58.8-131.3 135.8 0 79.9 50.3 134.7 131.3 134.7 61.3 0 101-27.6 120.1-86.3H509c-6.7 21.9-34.3 33.5-55.7 33.5-41.3 0-63-24.2-63-65.3h185.1c.3-4.2.6-8.7.6-13.2zM390.4 274c2.3-33.7 24.7-54.8 58.5-54.8 35.4 0 53.2 20.8 56.2 54.8H390.4z" class=""></path>
                        </svg>
                    </a>
                <?php } ?>
                <?php if ($instagramUrl = $author->getInstagram()) { ?>
                    <a class="social-instagram bg-gray-200 hover:bg-gray-100 p-2 text-gray-700 inline-flex items-center"
                       target="_blank"
                       rel="noreferrer"
                       href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($instagramUrl)) ?>"
                    >
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Share on')) ?> Instagram
                        </span>
                        <svg class="w-5 h-5 fill-current" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="instagram" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" class=""></path>
                        </svg>
                    </a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
